import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { redirect } from "next/navigation";
import Cookies from "js-cookie";
import { getAuthUser } from "@/lib/auth";
import { cookies } from "next/headers";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLogin = cookies().get("ACCESS_TOKEN")
  if (!isLogin) {
    redirect('/login')
  }

  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
